package quintwong.pojo;

public class Hero {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero.hp
     *
     * @mbg.generated
     */
    private Float hp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero.damage
     *
     * @mbg.generated
     */
    private Integer damage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero.id
     *
     * @return the value of hero.id
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero.id
     *
     * @param id the value for hero.id
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero.name
     *
     * @return the value of hero.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero.name
     *
     * @param name the value for hero.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero.hp
     *
     * @return the value of hero.hp
     * @mbg.generated
     */
    public Float getHp() {
        return hp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero.hp
     *
     * @param hp the value for hero.hp
     * @mbg.generated
     */
    public void setHp(Float hp) {
        this.hp = hp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero.damage
     *
     * @return the value of hero.damage
     * @mbg.generated
     */
    public Integer getDamage() {
        return damage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero.damage
     *
     * @param damage the value for hero.damage
     * @mbg.generated
     */
    public void setDamage(Integer damage) {
        this.damage = damage;
    }
}